### ISSUE TITLE
Рефакторинг чуть-чуть.

### ISSUE THREAD

**Issue by jchouse** [hoho/jquery-bem#4]
Ты вот такии конструкции в одну строку писал для экономии места?
if (blockName === '*') { blockName = blockPrefixes + characterEncoding; }

Тогда может так?
blockName === '*' && blockName = blockPrefixes + characterEncoding;

**Comment by hoho** [comment]
Когда после ифа одна операция простая — я иногда для компактности в одну строку пишу. То, что ты предлагаешь — хардкорно и усложняет читаемость.

**Comment by tadatuta** [comment]
алсо не будет работать без скобок в правой части

**Comment by jchouse** [comment]
алсо будет, оператор присваивания имеет наименьший приоритет, меньше чем у него только у запятой

**Comment by jchouse** [comment]
Я имею ввиду раз ты все равно вытягиваешь в строчку то читаемость приблизительно одинаковая. Тогда и в строку вытягивать без надобности.

**Comment by tadatuta** [comment]
проблема не в том, что присваивание случится раньше, а в том, что без скобок произойдет попытка выполнить

``` javascript
(true && someVar) = 'string';
```

**Comment by jchouse** [comment]
А в этом плане да, Марат меня понял, я не об этом

**Comment by tadatuta** [comment]
Просто с учетом этого твой способ выигрывает всего 1 символ.

**Comment by jchouse** [comment]
Ну ок, ок. Вот только символ не 1 а 2, если не учитывать пробельные, а так да.
Но главный посыл был именно в читаемости. Оператор if в одну строку не читабельнее &&. Вот как бы о чем я писал.

**Comment by Flackus** [comment]
Это не issue, а обсуждение кодстайла в частном гитхабе.
Невежливо.

**Comment by jchouse** [comment]
Тебе вон, тоже не спиться. Зыкрываем:)

**Comment by hoho** [comment]
Дело не в количестве строк, а в логике. Когда есть иф, то сразу понятно, что если это, то то-то. В общем, в данном случае лучше оставить дополнительный символ.
