### ISSUE TITLE
Расширение/Наследование (extend)

### ISSUE THREAD

**Issue by mbakirov** [hoho/jquery-bem#5]
Привет! В методе declCallback есть строки:

```
            if (isDecl && (mapKey in _declMap)) {
                $.error('Redeclaration in ' + self._c);
            }

            if (!isDecl && !(mapKey in _declMap)) {
                $.error('Not declared in ' + self._c);
            }
```

Как выяснилось, из-за них я не могу, расширяя блок, определить новые методы, модификаторы и элементы. Правильно ли это?

Например, у меня есть b-form, который описывает общее поведение форм (валидация, типы полей), но на одной странице я хочу расширить форму и хочу к ней написать метод "fillCities" – автозаполнение поля с городами.

```
$.BEM.extend('b-form') .onCall('fillCities', function(){ ... });
```

Я в своей копии плагина закомментировал эти строки и все работает корректно. В чем может быть подвох?

**Comment by hoho** [comment]
Привет. Я по историческим причинам отделил изначальные объявления от расширений и сделал так, чтобы их нельзя было смешивать. Основная логика, которая мной двигала, была, видимо, что нужно явно понимать, расширяешь ты блок или доопределяешь, это облегчает поиск ошибок в случаях, когда ты меняешь API блока и убираешь декларацию чего-то (в этом случае расширения этой декларации падают на этапе запуска).

То есть если ты в `$.BEM.extend()` будешь добавлять реакцию на модификатор или метод, которого не было ранее — будет исключение (возможно, текст не очень очевидный).

Если в `$.BEM.decl()` добавлять реакцию на модификатор или метод, который уже существует — тоже будет исключение.

На практике, если блок доопределяется и ему нужно расширить поведение по уже ранее декларированной части и определить новый метод, то нужно делать это в два вызова:

``` js
// Изначальная декларация.
$.BEM.decl('b-form')
    .onMod('js', function() { alert('init'); })
    .onCall('validate', function() { alert('ololo'); });

// Расширение и доопределение.
$.BEM.extend('b-form')
    .onMod('js', function($super) { $super.apply(this, Array.prototype.slice.call(arguments, 1)); });
$.BEM.decl('b-form')
    .onCall('fillCities', function() { alert('alala'); });


$('%b-form').bemMod('js', true)
$('%b-form').bemCall('validate');
$('%b-form').bemCall('fillCities');
```
