### ISSUE TITLE
How get child elems?

### ISSUE THREAD

**Issue by belozer** [hoho/jquery-bem#7]
Example:
$('%b-block').elem('elem1')

https://github.com/zenwalker/jquery-bem

**Comment by hoho** [comment]
``` js
$('%b-block(elem1)')
```

— return all `elem1` elements of all `b-block` blocks.

You can be more specific with the queries:

``` js
$('%b-block1 .some-class %b-block2(elem)')
```

— find all `elem` elements of all `b-block2` blocks which are inside a node with `some-class` class which is inside `b-block1` block.

Or you can use jQuery traverse functions:

``` js
$('%b-block').find('%b-block(elem1)').eq(0)
```

http://xslc.org/jquery-bem/#find
